### ISSUE TITLE
来自中国的大学生寻求项目求助

### ISSUE THREAD

**Issue by summer1127** [ruisizhang123/REMARK-LLM#1]
学姐您好，我想请问一下REMARK-LLM这个项目如果不下载huggingface的话，跑不起来这个项目，没有t5该如何运行
![image](https://github.com/user-attachments/assets/256642e4-aa6f-434f-94fe-954c0fbdcf61)
打扰您了

**Comment by ruisizhang123** [comment]
The huggingface package is imported from this folder `https://github.com/ruisizhang123/REMARK-LLM/tree/main/transformers`, instead of from source.

Maybe you can either (1) create a new conda env with `requirements.txt`, and see if the code would work; or (2) check if the tokenizer is downloaded properly from [line](https://github.com/ruisizhang123/REMARK-LLM/blob/aff7f80956f92c6d6bf412f0b9f132ef918d00f5/transformers/tokenization_utils_base.py#L1721)
