### ISSUE TITLE
Questions about baselines

### ISSUE THREAD

**Issue by yifeiZHA0** [ruisizhang123/REMARK-LLM#3]
Hello, I am wondering when implementing the baselines. In KGW's paper, they do not embed multiple bits information as watermark. So how to embed 4, 8, 16 bits information using KGW, the result for 4, 8, 16 bits is exactly same in table 3 and 4. 

Thank you!

**Comment by ruisizhang123** [comment]
Thank you for your interest in our work. As mentioned, "For KGW, we follow their paper setting [17] and consider the watermarking to be successful if the z-score of the watermark extraction exceeds 4."

That is, we report the WER as $\frac{NumSample(z-score>4)}{TotalSample}$, which is why they are the same in table3 and table4.
